import { NextApiRequest, NextApiResponse } from 'next';
import handler from './message';

// Mock dependencies
jest.mock('../../../lib/ai/core', () => ({
    askAI: jest.fn(),
}));
jest.mock('../../../lib/rate-limit', () => ({
    checkRateLimit: jest.fn(),
}));
jest.mock('../../../lib/auth/admin-check', () => ({
    checkIsAdmin: jest.fn(),
}));

import { askAI } from '../../../lib/ai/core';
import { checkRateLimit } from '../../../lib/rate-limit';
import { checkIsAdmin } from '../../../lib/auth/admin-check';

describe('Chat API', () => {
    let mockReq: Partial<NextApiRequest>;
    let mockRes: Partial<NextApiResponse>;
    let jsonMock: jest.Mock;
    let statusMock: jest.Mock;
    let endMock: jest.Mock;

    beforeEach(() => {
        jest.clearAllMocks();

        jsonMock = jest.fn();
        statusMock = jest.fn().mockReturnValue({ json: jsonMock, end: jest.fn() });
        endMock = jest.fn();

        mockReq = {
            method: 'POST',
            body: {
                message: 'Привет',
                history: [],
            },
            headers: {},
            socket: { remoteAddress: '127.0.0.1' } as any
        };

        mockRes = {
            status: statusMock,
            end: endMock,
            setHeader: jest.fn(),
        };

        // Default mock implementations
        (checkIsAdmin as jest.Mock).mockResolvedValue(false);
        (checkRateLimit as jest.Mock).mockResolvedValue({ success: true });
        (askAI as jest.Mock).mockResolvedValue({ reply: 'Здравствуйте!', handoffRequired: false });
    });

    it('returns 405 if method is not POST or OPTIONS', async () => {
        mockReq.method = 'GET';
        await handler(mockReq as NextApiRequest, mockRes as NextApiResponse);
        expect(statusMock).toHaveBeenCalledWith(405);
        expect(jsonMock).toHaveBeenCalledWith({ error: 'Method Not Allowed' });
    });

    it('handles OPTIONS preflight properly', async () => {
        mockReq.method = 'OPTIONS';
        await handler(mockReq as NextApiRequest, mockRes as NextApiResponse);
        expect(statusMock).toHaveBeenCalledWith(200);
    });

    it('returns error if message body is missing', async () => {
        mockReq.body = { message: '' }; // empty
        await handler(mockReq as NextApiRequest, mockRes as NextApiResponse);
        expect(statusMock).toHaveBeenCalledWith(400);
        expect(jsonMock).toHaveBeenCalledWith({ error: 'Message is required' });
    });

    it('detects strong pricing keywords and avoids AI call (handoff)', async () => {
        mockReq.body = { message: 'сколько стоит диван?', history: [] };
        await handler(mockReq as NextApiRequest, mockRes as NextApiResponse);

        expect(askAI).not.toHaveBeenCalled();
        expect(statusMock).toHaveBeenCalledWith(200);
        // "Я не подсказываю по стоимости..."
        expect(jsonMock).toHaveBeenCalledWith(expect.objectContaining({
            handoffRequired: true,
            reply: expect.stringContaining('по стоимости или покупке')
        }));
    });

    it('calls AI and returns standard reply', async () => {
        mockReq.body = { message: 'подойдет для гостиной?', history: [] };
        await handler(mockReq as NextApiRequest, mockRes as NextApiResponse);

        expect(askAI).toHaveBeenCalledTimes(1);
        expect(statusMock).toHaveBeenCalledWith(200);
        expect(jsonMock).toHaveBeenCalledWith({
            reply: 'Здравствуйте!',
            handoffRequired: false
        });
    });

    it('enforces rate limit for standard users', async () => {
        (checkRateLimit as jest.Mock).mockResolvedValue({ success: false });

        await handler(mockReq as NextApiRequest, mockRes as NextApiResponse);

        expect(askAI).not.toHaveBeenCalled();
        expect(statusMock).toHaveBeenCalledWith(200);
        expect(jsonMock).toHaveBeenCalledWith({
            reply: 'Лимит сообщений исчерпан. Пожалуйста, свяжитесь с нами по телефону.'
        });
    });

    it('detects commerce content generated by AI and forces handoff', async () => {
        mockReq.body = { message: 'А вот если?', history: [] };
        // AI sneaks a price response in
        (askAI as jest.Mock).mockResolvedValue({ reply: 'Это стоит 14000 руб', handoffRequired: false });

        await handler(mockReq as NextApiRequest, mockRes as NextApiResponse);

        expect(statusMock).toHaveBeenCalledWith(200);
        // It should forcefully override the AI's reply and require handoff
        expect(jsonMock).toHaveBeenCalledWith(expect.objectContaining({
            handoffRequired: true,
            reply: expect.stringContaining('по стоимости или покупке')
        }));
    });
});
